name: First Python CI
on:
  push:
    branches: [ "main" ]
jobs:
    basic-tests:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v3
        with: 
          python-version: 3.12
      - name: Install dependencies
        run: python -m pip install black pytest
      - name: Test with pytest
        run: pytest       
